const router = require('express').Router()
const { error } = require('../controllers/errorController')
const { notFound } = require('../controllers/notFoundController')

const Attraction = require('./attraction')
const AttractionImage = require('./attractionImage')
const TourPackage = require('./tourPackage')
const TourImage = require('./tourImage')
const Vehicle = require('./vehicle')
const TicketBooking = require('./ticketBooking')
const TourBooking = require('./tourBooking')
const Contact = require('./contact')
const ContactImage = require('./contactImage')
const Comment = require('./comment')
const Article = require('./article')
const ArticleImage = require('./articleImage')
const User = require('./user')

router.use("/api/v1/attractions", Attraction)
router.use("/api/v1/attraction/image", AttractionImage)
router.use("/api/v1/tours", TourPackage)
router.use("/api/v1/tour/image", TourImage)
router.use("/api/v1/vehicles", Vehicle)
router.use("/api/v1/ticket/booking", TicketBooking)
router.use("/api/v1/tour/booking", TourBooking)
router.use("/api/v1/contacts", Contact)
router.use("/api/v1/contact/image", ContactImage)
router.use("/api/v1/comments", Comment)
router.use("/api/v1/articles", Article)
router.use("/api/v1/article/image", ArticleImage)
router.use("/api/v1/user", User)
router.use(notFound)
router.use(error)

module.exports = router